"""add per-design preferences to design_sessions

Revision ID: 2bebb51afeca
Revises: f33fc04aa9c9
Create Date: 2026-09-06 21:19:55.403804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2bebb51afeca'
down_revision: Union[str, None] = 'f33fc04aa9c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('design_sessions', sa.Column('preferred_style', sa.String(length=50), nullable=True))
    op.add_column('design_sessions', sa.Column('preferred_colors', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('design_sessions', sa.Column('budget', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column(
        'design_sessions',
        sa.Column('currency', sa.String(length=3), nullable=False, server_default='INR'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('design_sessions', 'currency')
    op.drop_column('design_sessions', 'budget')
    op.drop_column('design_sessions', 'preferred_colors')
    op.drop_column('design_sessions', 'preferred_style')
    # ### end Alembic commands ###
