"""initial schema: all 16 tables

Revision ID: f33fc04aa9c9
Revises: 
Create Date: 2026-09-06 20:23:16.580284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'f33fc04aa9c9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Required for design_principles.embedding (pgvector, decision D006a).
    # Must run before any table using the `vector` type is created.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('design_principles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('category', sa.Enum('CLEARANCE', 'STYLE', 'COLOR', 'LIGHTING', 'ROOM_TYPE', name='principle_category'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('applies_to_room_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('applies_to_styles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_note', sa.String(length=300), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_design_principles'))
    )
    op.create_index(op.f('ix_design_principles_code'), 'design_principles', ['code'], unique=True)
    op.create_table('furniture_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('style_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('width_cm', sa.Float(), nullable=False),
    sa.Column('depth_cm', sa.Float(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('data_source', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_furniture_catalog'))
    )
    op.create_index(op.f('ix_furniture_catalog_category'), 'furniture_catalog', ['category'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('design_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('room_type', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ANALYZING', 'READY', 'ERROR', name='session_status'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_design_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_design_sessions'))
    )
    op.create_index(op.f('ix_design_sessions_user_id'), 'design_sessions', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('default_style', sa.String(length=50), nullable=True),
    sa.Column('default_colors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('default_budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_preferences'))
    )
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('PREPROCESS', 'ROOM_ANALYSIS', 'STYLE_RECOGNITION', 'RECOMMENDATION', 'LAYOUT_OPTIMIZATION', 'VISUALIZATION', name='job_stage'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'DONE', 'FAILED', name='job_status'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['design_sessions.id'], name=op.f('fk_jobs_session_id_design_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index(op.f('ix_jobs_session_id'), 'jobs', ['session_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('budget', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('within_budget', sa.Boolean(), nullable=False),
    sa.Column('palette', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['design_sessions.id'], name=op.f('fk_recommendations_session_id_design_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations'))
    )
    op.create_index(op.f('ix_recommendations_session_id'), 'recommendations', ['session_id'], unique=False)
    op.create_table('room_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('original_path', sa.String(length=500), nullable=False),
    sa.Column('processed_path', sa.String(length=500), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('quality_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['design_sessions.id'], name=op.f('fk_room_images_session_id_design_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room_images'))
    )
    op.create_index(op.f('ix_room_images_file_hash'), 'room_images', ['file_hash'], unique=False)
    op.create_index(op.f('ix_room_images_session_id'), 'room_images', ['session_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('structured_deltas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], name=op.f('fk_feedback_recommendation_id_recommendations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['design_sessions.id'], name=op.f('fk_feedback_session_id_design_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback'))
    )
    op.create_index(op.f('ix_feedback_session_id'), 'feedback', ['session_id'], unique=False)
    op.create_table('layouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('layout_score', sa.Float(), nullable=False),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('constraints_satisfied', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('algorithm', sa.String(length=50), nullable=False),
    sa.Column('iterations', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], name=op.f('fk_layouts_recommendation_id_recommendations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_layouts'))
    )
    op.create_index(op.f('ix_layouts_recommendation_id'), 'layouts', ['recommendation_id'], unique=False)
    op.create_table('recommendation_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('catalog_item_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('ADD', 'KEEP', 'REMOVE', 'REPLACE', name='recommendation_action'), nullable=False),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['catalog_item_id'], ['furniture_catalog.id'], name=op.f('fk_recommendation_items_catalog_item_id_furniture_catalog'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], name=op.f('fk_recommendation_items_recommendation_id_recommendations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_items'))
    )
    op.create_index(op.f('ix_recommendation_items_recommendation_id'), 'recommendation_items', ['recommendation_id'], unique=False)
    op.create_table('room_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('floor_polygon', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('free_space_ratio', sa.Float(), nullable=True),
    sa.Column('room_width_cm', sa.Float(), nullable=True),
    sa.Column('room_length_cm', sa.Float(), nullable=True),
    sa.Column('scale_source', sa.Enum('USER_PROVIDED', 'ESTIMATED', 'UNKNOWN', name='scale_source'), nullable=False),
    sa.Column('model_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['room_images.id'], name=op.f('fk_room_analyses_image_id_room_images'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room_analyses'))
    )
    op.create_index(op.f('ix_room_analyses_image_id'), 'room_analyses', ['image_id'], unique=False)
    op.create_table('detected_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('class_label', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.Enum('DETECTION', 'SEGMENTATION', name='detection_source'), nullable=False),
    sa.Column('area_px', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['room_analyses.id'], name=op.f('fk_detected_objects_analysis_id_room_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_detected_objects'))
    )
    op.create_index(op.f('ix_detected_objects_analysis_id'), 'detected_objects', ['analysis_id'], unique=False)
    op.create_table('layout_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('layout_id', sa.Integer(), nullable=False),
    sa.Column('catalog_item_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('x_cm', sa.Float(), nullable=False),
    sa.Column('y_cm', sa.Float(), nullable=False),
    sa.Column('width_cm', sa.Float(), nullable=False),
    sa.Column('depth_cm', sa.Float(), nullable=False),
    sa.Column('rotation_deg', sa.Float(), nullable=False),
    sa.Column('is_existing', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['catalog_item_id'], ['furniture_catalog.id'], name=op.f('fk_layout_objects_catalog_item_id_furniture_catalog'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['layout_id'], ['layouts.id'], name=op.f('fk_layout_objects_layout_id_layouts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_layout_objects'))
    )
    op.create_index(op.f('ix_layout_objects_layout_id'), 'layout_objects', ['layout_id'], unique=False)
    op.create_table('style_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('predicted_style', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('alternatives', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('abstained', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['room_analyses.id'], name=op.f('fk_style_predictions_analysis_id_room_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_style_predictions'))
    )
    op.create_index(op.f('ix_style_predictions_analysis_id'), 'style_predictions', ['analysis_id'], unique=False)
    op.create_table('visualizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('layout_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('prompt_used', sa.Text(), nullable=True),
    sa.Column('structure_preserving', sa.Boolean(), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['layout_id'], ['layouts.id'], name=op.f('fk_visualizations_layout_id_layouts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visualizations'))
    )
    op.create_index(op.f('ix_visualizations_layout_id'), 'visualizations', ['layout_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visualizations_layout_id'), table_name='visualizations')
    op.drop_table('visualizations')
    op.drop_index(op.f('ix_style_predictions_analysis_id'), table_name='style_predictions')
    op.drop_table('style_predictions')
    op.drop_index(op.f('ix_layout_objects_layout_id'), table_name='layout_objects')
    op.drop_table('layout_objects')
    op.drop_index(op.f('ix_detected_objects_analysis_id'), table_name='detected_objects')
    op.drop_table('detected_objects')
    op.drop_index(op.f('ix_room_analyses_image_id'), table_name='room_analyses')
    op.drop_table('room_analyses')
    op.drop_index(op.f('ix_recommendation_items_recommendation_id'), table_name='recommendation_items')
    op.drop_table('recommendation_items')
    op.drop_index(op.f('ix_layouts_recommendation_id'), table_name='layouts')
    op.drop_table('layouts')
    op.drop_index(op.f('ix_feedback_session_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_room_images_session_id'), table_name='room_images')
    op.drop_index(op.f('ix_room_images_file_hash'), table_name='room_images')
    op.drop_table('room_images')
    op.drop_index(op.f('ix_recommendations_session_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_jobs_session_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_design_sessions_user_id'), table_name='design_sessions')
    op.drop_table('design_sessions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_furniture_catalog_category'), table_name='furniture_catalog')
    op.drop_table('furniture_catalog')
    op.drop_index(op.f('ix_design_principles_code'), table_name='design_principles')
    op.drop_table('design_principles')
    # ### end Alembic commands ###
